import { Account } from "../../financial/accounting/Account.js";
import { AccountComplement } from "../../financial/accounting/AccountComplement.js";
import { Currency } from "../../financial/Currency.js";
import { FiscalProfileProduct } from "../../fiscal/FiscalProfileProduct.js";
import { ProductPacking } from "../../catalog/product/ProductPacking.js";
import { Purchase } from "./Purchase.js";
import { TaxationOperation } from "../../fiscal/taxation/TaxationOperation.js";
import { TaxationRule } from "../../fiscal/taxation/TaxationRule.js";
import { Unit } from "../../catalog/product/Unit.js";

export class PurchaseItem {
  id!: number;
  purchase!: Purchase;
  productPacking!: ProductPacking;
  fiscalProfileProduct!: FiscalProfileProduct;
  taxationRule!: TaxationRule;
  taxationOperation!: TaxationOperation;
  priceListValue!: number;
  unit!: Unit;
  quantity!: number;
  internalQuantity!: number;
  servedQuantity!: number;
  unitValue!: number;
  currency!: Currency;
  productValue!: number;
  discountType!: string;
  discountAmount!: number;
  discountValue!: number;
  otherValues!: Map<string,number>;
  operationValue!: number;
  insideTaxValue!: number;
  outsideTaxValue!: number;
  totalValue!: number;
  taxCompensationValue!: number;
  effectiveValue!: number;
  account!: Account;
  accountComplement!: AccountComplement;
  tags!: string;
  properties!: Object;
}
