import ControlCatalogCategory from "./ControlCatalogCategory.js";
import ControlCatalogCompanyCompany from "./ControlCatalogCompanyCompany.js";
import ControlCatalogCompanySociety from "./ControlCatalogCompanySociety.js";
import ControlCatalogLocationCity from "./ControlCatalogLocationCity.js";
import ControlCatalogLocationCountry from "./ControlCatalogLocationCountry.js";
import ControlCatalogLocationState from "./ControlCatalogLocationState.js";
import ControlCatalogPersonPerson from "./ControlCatalogPersonPerson.js";
import ControlCatalogPersonPersonAddress from "./ControlCatalogPersonPersonAddress.js";
import ControlCatalogPersonPersonGroup from "./ControlCatalogPersonPersonGroup.js";
import ControlCatalogProductCodeConversionList from "./ControlCatalogProductCodeConversionList.js";
import ControlCatalogProductDimension from "./ControlCatalogProductDimension.js";
import ControlCatalogProductProduct from "./ControlCatalogProductProduct.js";
import ControlCatalogProductProductPacking from "./ControlCatalogProductProductPacking.js";
import ControlCatalogProductProductProfile from "./ControlCatalogProductProductProfile.js";
import ControlCatalogProductProductVariant from "./ControlCatalogProductProductVariant.js";
import ControlCatalogProductUnit from "./ControlCatalogProductUnit.js";
import ControlCheckBox from "./ControlCheckBox.js";
import ControlColor from "./ControlColor.js";
import ControlCommercialContractContract from "./ControlCommercialContractContract.js";
import ControlCommercialContractContractIndex from "./ControlCommercialContractContractIndex.js";
import ControlCommercialContractContractItem from "./ControlCommercialContractContractItem.js";
import ControlCommercialContractContractProfile from "./ControlCommercialContractContractProfile.js";
import ControlCommercialPaymentType from "./ControlCommercialPaymentType.js";
import ControlCommercialPriceList from "./ControlCommercialPriceList.js";
import ControlDatetime from "./ControlDatetime.js";
import ControlFinancialAccountingAccount from "./ControlFinancialAccountingAccount.js";
import ControlFinancialAccountingAccountCategory from "./ControlFinancialAccountingAccountCategory.js";
import ControlFinancialAccountingAccountChart from "./ControlFinancialAccountingAccountChart.js";
import ControlFinancialAccountingAccountFiscalYear from "./ControlFinancialAccountingAccountFiscalYear.js";
import ControlFinancialAccountingResultCenter from "./ControlFinancialAccountingResultCenter.js";
import ControlFinancialAccountingResultCenterChart from "./ControlFinancialAccountingResultCenterChart.js";
import ControlFinancialBillingWallet from "./ControlFinancialBillingWallet.js";
import ControlFinancialCreditCreditLine from "./ControlFinancialCreditCreditLine.js";
import ControlFinancialCurrency from "./ControlFinancialCurrency.js";
import ControlFinancialPayable from "./ControlFinancialPayable.js";
import ControlFinancialReceivable from "./ControlFinancialReceivable.js";
import ControlFiscalFiscalProfileOperation from "./ControlFiscalFiscalProfileOperation.js";
import ControlFiscalFiscalProfilePerson from "./ControlFiscalFiscalProfilePerson.js";
import ControlFiscalFiscalProfileProduct from "./ControlFiscalFiscalProfileProduct.js";
import ControlFiscalFiscalRegion from "./ControlFiscalFiscalRegion.js";
import ControlFiscalIncomingInvoice from "./ControlFiscalIncomingInvoice.js";
import ControlFiscalInvoiceSeries from "./ControlFiscalInvoiceSeries.js";
import ControlFiscalTaxationTax from "./ControlFiscalTaxationTax.js";
import ControlFiscalTaxationTaxationOperation from "./ControlFiscalTaxationTaxationOperation.js";
import ControlFiscalVolume from "./ControlFiscalVolume.js";
import ControlHideAndSeek from "./ControlHideAndSeek.js";
import ControlInputNumber from "./ControlInputNumber.js";
import ControlMaterialAddress from "./ControlMaterialAddress.js";
import ControlMaterialAddressProfile from "./ControlMaterialAddressProfile.js";
import ControlMaterialHandlintUnit from "./ControlMaterialHandlintUnit.js";
import ControlMaterialIncomingList from "./ControlMaterialIncomingList.js";
import ControlMaterialIncomingRequest from "./ControlMaterialIncomingRequest.js";
import ControlMaterialInventory from "./ControlMaterialInventory.js";
import ControlMaterialLot from "./ControlMaterialLot.js";
import ControlMaterialOutgoingList from "./ControlMaterialOutgoingList.js";
import ControlMaterialPickingOrder from "./ControlMaterialPickingOrder.js";
import ControlMaterialPickingProfile from "./ControlMaterialPickingProfile.js";
import ControlMaterialProductProfile from "./ControlMaterialProductProfile.js";
import ControlMaterialQuality from "./ControlMaterialQuality.js";
import ControlMaterialReservation from "./ControlMaterialReservation.js";
import ControlMaterialReservationTarget from "./ControlMaterialReservationTarget.js";
import ControlMaterialSerial from "./ControlMaterialSerial.js";
import ControlMaterialStockCluster from "./ControlMaterialStockCluster.js";
import ControlMaterialStockType from "./ControlMaterialStockType.js";
import ControlMaterialWarehouse from "./ControlMaterialWarehouse.js";
import ControlSalePriceFormation from "./ControlSalePriceFormation.js";
import ControlSalePriceList from "./ControlSalePriceList.js";
import ControlSaleSale from "./ControlSaleSale.js";
import ControlSaleSaleProfile from "./ControlSaleSaleProfile.js";
import ControlSelect from "./ControlSelect.js";
import ControlShippingShipment from "./ControlShippingShipment.js";
import ControlSupplyProductionOperationType from "./ControlSupplyProductionOperationType.js";
import ControlSupplyProductionProductionOrder from "./ControlSupplyProductionProductionOrder.js";
import ControlSupplyProductionProductionProfile from "./ControlSupplyProductionProductionProfile.js";
import ControlSupplyProductionProductionStep from "./ControlSupplyProductionProductionStep.js";
import ControlSupplyPurchasePriceList from "./ControlSupplyPurchasePriceList.js";
import ControlSupplyPurchasePurchase from "./ControlSupplyPurchasePurchase.js";
import ControlSupplyPurchasePurchaseItem from "./ControlSupplyPurchasePurchaseItem.js";
import ControlSupplyPurchasePurchaseProfile from "./ControlSupplyPurchasePurchaseProfile.js";
import ControlSupplyPurchaseQuoteItem from "./ControlSupplyPurchaseQuoteItem.js";
import ControlSvg from "./ControlSvg.js";
import ControlSwitch from "./ControlSwitch.js";
import ControlSwitches from "./ControlSwitches.js";
import ControlSystemAutomationAgent from "./ControlSystemAutomationAgent.js";
import ControlSystemDataDataSource from "./ControlSystemDataDataSource.js";
import ControlSystemImageImage from "./ControlSystemImageImage.js";
import ControlSystemIntegrationQueue from "./ControlSystemIntegrationQueue.js";
import ControlSystemIntegrationTopic from "./ControlSystemIntegrationTopic.js";
import ControlSystemMailMailerConfig from "./ControlSystemMailMailerConfig.js";
import ControlSystemPrintingPrinter from "./ControlSystemPrintingPrinter.js";
import ControlSystemReportReport from "./ControlSystemReportReport.js";
import ControlSystemSecurityAccessPoint from "./ControlSystemSecurityAccessPoint.js";
import ControlSystemSecurityAccessProfile from "./ControlSystemSecurityAccessProfile.js";
import ControlSystemSecurityGroup from "./ControlSystemSecurityGroup.js";
import ControlSystemSecurityKeyStore from "./ControlSystemSecurityKeyStore.js";
import ControlSystemSecurityRole from "./ControlSystemSecurityRole.js";
import ControlSystemSecurityUser from "./ControlSystemSecurityUser.js";
import ControlSystemWorkflowWorkflow from "./ControlSystemWorkflowWorkflow.js";
import ControlSystemWorkflowWorkflowNode from "./ControlSystemWorkflowWorkflowNode.js";
import ControlTag from "./ControlTag.js";
import ControlTags from "./ControlTags.js";
import ControlTagsView from "./ControlTagsView.js";
import ControlTemplate from "./ControlTemplate.js";
import ControlTextArea from "./ControlTextArea.js";

export function customElementsDefine() {
  customElements.define("ps-catalog-category", ControlCatalogCategory);
  customElements.define("ps-catalog-company-company", ControlCatalogCompanyCompany);
  customElements.define("ps-catalog-company-society", ControlCatalogCompanySociety);
  customElements.define("ps-catalog-location-city", ControlCatalogLocationCity);
  customElements.define("ps-catalog-location-country", ControlCatalogLocationCountry);
  customElements.define("ps-catalog-location-state", ControlCatalogLocationState);
  customElements.define("ps-catalog-person-person", ControlCatalogPersonPerson);
  customElements.define("ps-catalog-person-personaddress", ControlCatalogPersonPersonAddress);
  customElements.define("ps-catalog-person-persongroup", ControlCatalogPersonPersonGroup);
  customElements.define("ps-catalog-product-codeconversionlist", ControlCatalogProductCodeConversionList);
  customElements.define("ps-catalog-product-dimension", ControlCatalogProductDimension);
  customElements.define("ps-catalog-product-product", ControlCatalogProductProduct);
  customElements.define("ps-catalog-product-productpacking", ControlCatalogProductProductPacking);
  customElements.define("ps-catalog-product-productprofile", ControlCatalogProductProductProfile);
  customElements.define("ps-catalog-product-productvariant", ControlCatalogProductProductVariant);
  customElements.define("ps-catalog-product-unit", ControlCatalogProductUnit);
  customElements.define("ps-checkbox", ControlCheckBox);
  customElements.define("ps-commercial-contract-contract", ControlCommercialContractContract);
  customElements.define("ps-commercial-contract-contractindex", ControlCommercialContractContractIndex);
  customElements.define("ps-commercial-contract-contractitem", ControlCommercialContractContractItem);
  customElements.define("ps-commercial-contract-contractprofile", ControlCommercialContractContractProfile);
  customElements.define("ps-commercial-paymenttype", ControlCommercialPaymentType);
  customElements.define("ps-commercial-pricelist", ControlCommercialPriceList);
  customElements.define("ps-datetime", ControlDatetime);
  customElements.define("ps-financial-accounting-account", ControlFinancialAccountingAccount);
  customElements.define("ps-financial-accounting-accountcategory", ControlFinancialAccountingAccountCategory);
  customElements.define("ps-financial-accounting-accountchart", ControlFinancialAccountingAccountChart);
  customElements.define("ps-financial-accounting-accountfiscalyear", ControlFinancialAccountingAccountFiscalYear);
  customElements.define("ps-financial-accounting-resultcenter", ControlFinancialAccountingResultCenter);
  customElements.define("ps-financial-accounting-resultcenterchart", ControlFinancialAccountingResultCenterChart);
  customElements.define("ps-financial-billing-wallet", ControlFinancialBillingWallet);
  customElements.define("ps-financial-credit-creditline", ControlFinancialCreditCreditLine);
  customElements.define("ps-financial-currency", ControlFinancialCurrency);
  customElements.define("ps-financial-payable", ControlFinancialPayable);
  customElements.define("ps-financial-receivable", ControlFinancialReceivable);
  customElements.define("ps-fiscal-fiscalprofileoperation", ControlFiscalFiscalProfileOperation);
  customElements.define("ps-fiscal-fiscalprofileperson", ControlFiscalFiscalProfilePerson);
  customElements.define("ps-fiscal-fiscalprofileproduct", ControlFiscalFiscalProfileProduct);
  customElements.define("ps-fiscal-fiscalregion", ControlFiscalFiscalRegion);
  customElements.define("ps-fiscal-incominginvoice", ControlFiscalIncomingInvoice);
  customElements.define("ps-fiscal-invoiceseries", ControlFiscalInvoiceSeries);
  customElements.define("ps-fiscal-taxation-tax", ControlFiscalTaxationTax);
  customElements.define("ps-fiscal-taxation-taxationoperation", ControlFiscalTaxationTaxationOperation);
  customElements.define("ps-fiscal-volume", ControlFiscalVolume);
  customElements.define("ps-hide-and-seek", ControlHideAndSeek);
  customElements.define("ps-material-address", ControlMaterialAddress);
  customElements.define("ps-material-addressprofile", ControlMaterialAddressProfile);
  customElements.define("ps-material-handlingunit", ControlMaterialHandlintUnit);
  customElements.define("ps-material-incominglist", ControlMaterialIncomingList);
  customElements.define("ps-material-incomingrequest", ControlMaterialIncomingRequest);
  customElements.define("ps-material-inventory", ControlMaterialInventory);
  customElements.define("ps-material-lot", ControlMaterialLot);
  customElements.define("ps-material-outgoinglist", ControlMaterialOutgoingList);
  customElements.define("ps-material-pickingorder", ControlMaterialPickingOrder);
  customElements.define("ps-material-pickingprofile", ControlMaterialPickingProfile);
  customElements.define("ps-material-productprofile", ControlMaterialProductProfile);
  customElements.define("ps-material-quality", ControlMaterialQuality);
  customElements.define("ps-material-reservation", ControlMaterialReservation);
  customElements.define("ps-material-reservationtarget", ControlMaterialReservationTarget);
  customElements.define("ps-material-serial", ControlMaterialSerial);
  customElements.define("ps-material-stockcluster", ControlMaterialStockCluster);
  customElements.define("ps-material-stocktype", ControlMaterialStockType);
  customElements.define("ps-material-warehouse", ControlMaterialWarehouse);
  customElements.define("ps-sale-priceformation", ControlSalePriceFormation);
  customElements.define("ps-sale-pricelist", ControlSalePriceList);
  customElements.define("ps-sale-sale", ControlSaleSale);
  customElements.define("ps-sale-saleprofile", ControlSaleSaleProfile);
  customElements.define("ps-select", ControlSelect);
  customElements.define("ps-shipping-shipment", ControlShippingShipment);
  customElements.define("ps-supply-production-operationtype", ControlSupplyProductionOperationType);
  customElements.define("ps-supply-production-productionorder", ControlSupplyProductionProductionOrder);
  customElements.define("ps-supply-production-productionprofile", ControlSupplyProductionProductionProfile);
  customElements.define("ps-supply-production-productionstep", ControlSupplyProductionProductionStep);
  customElements.define("ps-supply-purchase-pricelist", ControlSupplyPurchasePriceList);
  customElements.define("ps-supply-purchase-purchase", ControlSupplyPurchasePurchase);
  customElements.define("ps-supply-purchase-purchaseitem", ControlSupplyPurchasePurchaseItem);
  customElements.define("ps-supply-purchase-purchaseprofile", ControlSupplyPurchasePurchaseProfile);
  customElements.define("ps-supply-purchase-quoteitem", ControlSupplyPurchaseQuoteItem);
  customElements.define("ps-svg", ControlSvg);
  customElements.define("ps-switch", ControlSwitch);
  customElements.define("ps-switches", ControlSwitches);
  customElements.define("ps-system-automation-agent", ControlSystemAutomationAgent);
  customElements.define("ps-system-data-datasource", ControlSystemDataDataSource);
  customElements.define("ps-system-image-image", ControlSystemImageImage);
  customElements.define("ps-system-integration-queue", ControlSystemIntegrationQueue);
  customElements.define("ps-system-integration-topic", ControlSystemIntegrationTopic);
  customElements.define("ps-system-mail-mailerconfig", ControlSystemMailMailerConfig);
  customElements.define("ps-system-printing-printer", ControlSystemPrintingPrinter);
  customElements.define("ps-system-report-report", ControlSystemReportReport);
  customElements.define("ps-system-security-accesspoint", ControlSystemSecurityAccessPoint);
  customElements.define("ps-system-security-accessprofile", ControlSystemSecurityAccessProfile);
  customElements.define("ps-system-security-group", ControlSystemSecurityGroup);
  customElements.define("ps-system-security-keystore", ControlSystemSecurityKeyStore);
  customElements.define("ps-system-security-role", ControlSystemSecurityRole);
  customElements.define("ps-system-security-user", ControlSystemSecurityUser);
  customElements.define("ps-system-workflow-workflow", ControlSystemWorkflowWorkflow);
  customElements.define("ps-system-workflow-workflownode", ControlSystemWorkflowWorkflowNode);
  customElements.define("ps-tag", ControlTag);
  customElements.define("ps-tags", ControlTags);
  customElements.define("ps-tags-view", ControlTagsView);
  customElements.define("ps-template", ControlTemplate);
  customElements.define("ps-textarea", ControlTextArea);
  customElements.define("z-color", ControlColor);
  customElements.define("z-input-number", ControlInputNumber);
}
