import { Company } from "../catalog/company/Company.js";
import { FiscalProfileOperation } from "./FiscalProfileOperation.js";
import { FiscalProfilePerson } from "./FiscalProfilePerson.js";
import { InvoiceSeries } from "./InvoiceSeries.js";
import { JournalEntry } from "../financial/accounting/JournalEntry.js";
import { OutgoingList } from "../material/OutgoingList.js";
import { Person } from "../catalog/person/Person.js";
import { PersonAddress } from "../catalog/person/PersonAddress.js";
import { Shipment } from "../shipping/Shipment.js";
import { Workflow } from "../system/workflow/Workflow.js";
import { Workpiece } from "../system/workflow/Workpiece.js";

export class OutgoingInvoice {
  status!: string;
  outgoingList!: OutgoingList;
  shipment!: Shipment;
  id!: number;
  source!: string;
  company!: Company;
  fiscalProfileOperation!: FiscalProfileOperation;
  workflow!: Workflow;
  workpiece!: Workpiece;
  person!: Person;
  personAddressShipping!: PersonAddress;
  personShipping!: Person;
  freightType!: string;
  fiscalProfilePerson!: FiscalProfilePerson;
  returned!: boolean;
  invoiceSeries!: InvoiceSeries;
  number!: number;
  date!: Date;
  issueDate!: Date;
  shippingDateTime!: Date;
  grossWeightKg!: number;
  netWeightKg!: number;
  volumeM3!: number;
  totalValue!: number;
  journalEntry!: JournalEntry;
  personSalesperson!: Person;
  tags!: string;
  properties!: Object;
}
